### ISSUE TITLE
Nested folder structure

### ISSUE THREAD

**Issue by BitBork** [Praxxian/lava-flow#49] opened 2024-01-28 21:36 UTC
Hi there, been using Obsidian md for notetaking and have **a lot** I'd like to import now that I got my world up and running on a server on the Forge, though I'm having some issues getting that sorted.

The error the console gives is that there are more subfolders in my Obsidian vault than (vanilla) Foundry allows you to make. Pairing it up with the 'Moar Folders' module does not bypass that however. Is there a possible fix for this, so I won't have to reorganize my entire folder structure? I can imagine the hardcap Foundry sets on subfolders might pose a problem, so maybe a compatibility with the Moar Folders module could be a (hot)fix?

At first I was also having some issues importing anything because of (what I'm guessing) was caused by having active Obsidian community plugins, but after disabling those (and barring the aformentioned issue), the console also gave me errors in regards to images not wanting to upload.

I don't have screenshots on hand but I can recreate the console errors if you'd like.

**Comment by Praxxian** [comment] 2024-02-14 07:15
I can take a look at integrating with Moar Folders. At the very least, it would be better to still allow one to import, but just not try to create folders beyond Foundry's limit.

There is also a bug open for the image upload issue: #40. Someone already identified a fix, but I have to review the changes still.

**Comment by Praxxian** [comment] 2024-04-02 01:35
@BitBork what version of Foundry and Moar Folders are you using? I was checking out the module and in theory this should work because it's just adjusting the setting foundry uses already. However, when I tried this Foundry `11.306` and the latest Moar Folders `1.1.3`, MF just does not seem to work in v11 on its own.

In the absence of MF in v11, I am not sure what the expected behavior should be. If the max folder depth is exceeded, should it just try to dump everything in the last valid folder level? Prepend folder names in excess of the maximum to the journal entry name, maybe?

BTW the latest release of this module (3.1.0) adds a new feature to combine notes into a single Journal Entry with multiple pages. Not sure if that avoids the folder depth issue for you. If it does, this issue might be moot anyway.

**Comment by BitBork** [comment] 2024-05-02 15:25
Hi there @Praxxian ,

Sorry, have been on a hiatus with D&D, too much going on. I'm using Foundry verstion 11 stable build 315 and Moar Folders v1.1.3 . Not sure if any there've been any updates since, be it for MF or FVTT (always a bit scared to update in case it all breaks). I'll have another look soon-ish to see if the issue persists with the current versions still.

Hmm I see, that could definitely be a solution in combination with Monk's Enhanced Journal, as that makes it all a lot neater. I do generally still prefer to have a neat folder structure and especially like to keep my structure the same on both Obsidian and Foundry though.

I'll see what I can do with the current versions, updating the MF module, possibly updating Foundry etc. soon and get back to you.

**Comment by Praxxian** [comment] 2024-12-30 19:49
Looks like MF is no longer maintained. Not aware of any folder-depth module that works in v12+. I am going to close this, but feel free to let me know if you do have a module that increases folder depth _and_ it has compatibility issues.

**Closed by Praxxian** 2024-12-30 19:49 UTC
Labels: bug
